# Generated by Django 6.0.3 on 2026-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
